### ISSUE TITLE
RunTime Error : SQL Failed

### ISSUE THREAD

**Issue by Angrybeef1** [AdamGagorik/ffxiahbot#48]
Ok Need some help with this one. I checked the closed and open cases trying to resolve this. I have reinstalled Maria DB, FFXI from landseaboat, and pydarkstar several times. 

- I have 2 databases for servers one i use MYSQL on at port 3306, so i set up maria to run on 3310 for FFXI,
- I have set password, and verified several times that it is set correctly in the Config.yml file.
- I have verified the DB names is xidb which matches both the name and the config.yml
- I beleive the password ???? is a default setting you added to not show password when these files are sent.
- There are lines here that make me think the its not connecting **pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")**
- Windower connects to the server, I can play on said server, not sure why this is getting the errors.

Any assistance would be appreciated.

[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: config     = config.yaml
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: verbose    = True
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: silent     = False
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: hostname   = localhost
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: database   = xidb
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: username   = root
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: password   = ????
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: fail       = True
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: data       = ['items.csv']
[2024-05-03 22:19:03,711][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: name       = Zissou
[2024-05-03 22:19:03,712][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: restock    = 3600
[2024-05-03 22:19:03,712][MainProcess][MainThread][INFO ]: (0x259406ea2e8) Options: tick       = 30
[2024-05-03 22:19:03,712][MainProcess][MainThread][DEBUG]: (0x25943c7ae10) Database: init
[2024-05-03 22:19:03,712][MainProcess][MainThread][DEBUG]: (0x25943c9e240) Manager: init
[2024-05-03 22:19:03,712][MainProcess][MainThread][DEBUG]: (0x25943c9e2b0) Browser: init
[2024-05-03 22:19:03,712][MainProcess][MainThread][DEBUG]: (0x25943c9e390) Cleaner: init
[2024-05-03 22:19:03,712][MainProcess][MainThread][DEBUG]: (0x25943c9e2e8) Seller: init
[2024-05-03 22:19:03,712][MainProcess][MainThread][DEBUG]: (0x25943c9e550) Buyer: init
[2024-05-03 22:19:03,713][MainProcess][MainThread][DEBUG]: (0x25943c9e4a8) ItemList: init
[2024-05-03 22:19:03,713][MainProcess][MainThread][INFO ]: (0x25943c9e4a8) ItemList: loading item data...
[2024-05-03 22:19:03,713][MainProcess][MainThread][INFO ]: (0x25943c9e4a8) ItemList: load items.csv
[2024-05-03 22:19:03,977][MainProcess][MainThread][INFO ]: starting main loop...
[2024-05-03 22:19:03,977][MainProcess][MainThread][DEBUG]: time=0000000000.0 s last restock=0000000000.0 s next restock=0000003600.0 s
[2024-05-03 22:19:04,010][MainProcess][MainThread][ERROR]: caught SQL exception
Traceback (most recent call last):
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\default.py", line 451, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 882, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\_auth.py", line 265, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\_auth.py", line 122, in _roundtrip
    pkt = conn._read_packet()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\FFXI_Server\pydarkstar\pydarkstar\database.py", line 45, in scoped_session
    yield session
  File "G:\FFXI_Server\pydarkstar\pydarkstar\auction\worker.py", line 35, in scopped_session
    yield session
  File "G:\FFXI_Server\pydarkstar\pydarkstar\auction\manager.py", line 68, in buy_items
    for row in q:
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 3323, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 3345, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 3360, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 3338, in _connection_from_session
    conn = self.session.connection(**kw)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 1123, in connection
    execution_options=execution_options,
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 1129, in _connection_for_bind
    engine, execution_options
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 430, in _connection_for_bind
    conn = bind._contextual_connect()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2226, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2266, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\default.py", line 451, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 882, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\_auth.py", line 265, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\_auth.py", line 122, in _roundtrip
    pkt = conn._read_packet()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: http://sqlalche.me/e/e3q8)
[2024-05-03 22:19:04,016][MainProcess][MainThread][ERROR]: caught unhandled excetion
Traceback (most recent call last):
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\default.py", line 451, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 882, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\_auth.py", line 265, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\_auth.py", line 122, in _roundtrip
    pkt = conn._read_packet()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\FFXI_Server\pydarkstar\pydarkstar\database.py", line 45, in scoped_session
    yield session
  File "G:\FFXI_Server\pydarkstar\pydarkstar\auction\worker.py", line 35, in scopped_session
    yield session
  File "G:\FFXI_Server\pydarkstar\pydarkstar\auction\manager.py", line 68, in buy_items
    for row in q:
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 3323, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 3345, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 3360, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\query.py", line 3338, in _connection_from_session
    conn = self.session.connection(**kw)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 1123, in connection
    execution_options=execution_options,
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 1129, in _connection_for_bind
    engine, execution_options
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\orm\session.py", line 430, in _connection_for_bind
    conn = bind._contextual_connect()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2226, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2266, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 1536, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\base.py", line 2262, in _wrap_pool_connect
    return fn()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\pool\base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\sqlalchemy\engine\default.py", line 451, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 882, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\_auth.py", line 265, in caching_sha2_password_auth
    pkt = _roundtrip(conn, data)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\_auth.py", line 122, in _roundtrip
    pkt = conn._read_packet()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: http://sqlalche.me/e/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\FFXI_Server\pydarkstar\pydarkstar\logutils.py", line 47, in capture
    yield
  File "G:\FFXI_Server\pydarkstar\bin\broker.py", line 21, in <module>
    pydarkstar.apps.broker.run.main()
  File "G:\FFXI_Server\pydarkstar\pydarkstar\apps\broker\run.py", line 53, in main
    manager.buy_items(itemdata=idata)
  File "G:\FFXI_Server\pydarkstar\pydarkstar\auction\manager.py", line 115, in buy_items
    self.debug('skipping row %d', row.id)
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "G:\FFXI_Server\pydarkstar\pydarkstar\auction\worker.py", line 35, in scopped_session
    yield session
  File "C:\Users\rston\anaconda3\envs\pydarkstar\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "G:\FFXI_Server\pydarkstar\pydarkstar\database.py", line 61, in scoped_session
    raise RuntimeError('SQL Failed')
RuntimeError: SQL Failed
[2024-05-03 22:19:04,018][MainProcess][MainThread][INFO ]: exit

**Comment by Angrybeef1** [comment]
Ok So playing around with this some more...I reinstalled the DB for FFXI a few times again. This time I shutdown the MySQL db for WOW which i had on the 3306 port. I redid the FFXI db on that port this time and made adjustments everythign connects. I left mysql off and redid the db to 3310 and it wont connect again. I didnt see the port option on the config, Where woudl it be located at to adjust it to run on a different port?

**Comment by AdamGagorik** [comment]
I have added a new parameter to the config file that will allow you to change the port.

```yaml
config: 3306
```
